export const ADD_TODO = "ADD_TODO"
export const DELETE_TODO = "DELETE_TODO"
export const TODO_EDITED = "TODO_EDITED"
export const EDIT_TODO = "EDIT_TODO"
export const SAVETODO_EDIT = "SAVETODO_EDIT"
export const SAVE_TODO = "SAVE_TODO"
export const TOGGLE_CLASS = "TOGGLE_CLASS"